security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            entry_point: App\Security\LoginAuthenticator
            logout:
                path: app_logout      # Chemin pour la déconnexion
                target: app_home      # Redirection vers l'accueil après déconnexion

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password$, roles: PUBLIC_ACCESS }  # Ajout pour la page de mot de passe oublié
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/banned, roles: ROLE_BANNED }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
    
